definitions:
  loginmodel.LoginRequest:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  loginmodel.LoginResponse:
    properties:
      token:
        type: string
      valid:
        type: boolean
    type: object
  paymentmodel.PaymentModel:
    properties:
      id:
        example: 1
        format: int64
        type: integer
      name:
        example: account name
        type: string
      uuid:
        example: 550e8400-e29b-41d4-a716-446655440000
        format: uuid
        type: string
    type: object
  usermodel.User:
    properties:
      email:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /connect/token:
    post:
      consumes:
      - application/json
      description: Efetua login
      operationId: connect-token
      parameters:
      - description: LoginRequest
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/loginmodel.LoginRequest'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: qwerty
              type: string
          schema:
            $ref: '#/definitions/loginmodel.LoginResponse'
            type: object
      summary: Efetua login
  /payment/create:
    post:
      consumes:
      - application/json
      description: Cria um pagamento
      operationId: payment-create
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: qwerty
              type: string
          schema:
            $ref: '#/definitions/paymentmodel.PaymentModel'
            type: object
      summary: Cria um pagamento
  /user/create:
    post:
      consumes:
      - application/json
      description: Cria usuário
      operationId: connect-token
      parameters:
      - description: User
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/usermodel.User'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: qwerty
              type: string
          schema:
            $ref: '#/definitions/usermodel.User'
            type: object
      summary: Cria usuario
