definitions:
  model.Group:
    properties:
      name:
        type: string
    type: object
  model.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  model.LoginResponse:
    properties:
      token:
        type: string
      valid:
        type: boolean
    type: object
  model.PaymentModel:
    properties:
      name:
        example: account name
        type: string
      uuid:
        example: 550e8400-e29b-41d4-a716-446655440000
        format: uuid
        type: string
    type: object
  model.User:
    properties:
      email:
        type: string
      groupID:
        type: integer
      name:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /connect/token:
    post:
      consumes:
      - application/json
      description: Efetua login
      operationId: connect-token
      parameters:
      - description: LoginRequest
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.LoginRequest'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: qwerty
              type: string
          schema:
            $ref: '#/definitions/model.LoginResponse'
            type: object
      summary: Efetua login
  /group/create:
    post:
      consumes:
      - application/json
      description: Cria grupo de usuários
      operationId: group-create
      parameters:
      - description: Group
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.Group'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: qwerty
              type: string
          schema:
            $ref: '#/definitions/model.Group'
            type: object
      summary: Cria grupo de usuários
  /group/list:
    get:
      consumes:
      - application/json
      description: Lista de grupo de usuarios
      operationId: user-create
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: qwerty
              type: string
          schema:
            items:
              $ref: '#/definitions/model.Group'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Lista grupo de usuarios
  /payment/create:
    post:
      consumes:
      - application/json
      description: Cria um pagamento
      operationId: payment-create
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: qwerty
              type: string
          schema:
            $ref: '#/definitions/model.PaymentModel'
            type: object
      summary: Cria um pagamento
  /user/create:
    post:
      consumes:
      - application/json
      description: Cria usuário
      operationId: user-create
      parameters:
      - description: User
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.User'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: qwerty
              type: string
          schema:
            $ref: '#/definitions/model.User'
            type: object
      summary: Cria usuario
  /user/list:
    post:
      consumes:
      - application/json
      description: Lista de grupo de usuarios
      operationId: user-create
      parameters:
      - description: User
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.User'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: qwerty
              type: string
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Lista grupo de usuarios
