version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: hagadol23
      POSTGRES_USER: root
      POSTGRES_DB: cashdb
    volumes:
      - /Users/davidmadi/go/src/cashapi/db/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080