package main

import (
	"net/http"

	"github.com/gin-gonic/gin"

	authenticationcontroller "cashapi/src/controller/authentication"
	paymentcontroller "cashapi/src/controller/payment"
	usercontroller "cashapi/src/controller/user"

	"github.com/labstack/echo"
	ginSwagger "github.com/swaggo/gin-swagger"
	"github.com/swaggo/gin-swagger/swaggerFiles"

	//echoSwagger "github.com/swaggo/echo-swagger"
	_ "cashapi/docs" // docs is generated by Swag CLI, you have to import it.
	// docs is generated by Swag CLI, you have to import it.

	migration "cashapi/src/database/migration"
)

// @title CashAPI
// @version 1.0
// @description API para CashAPI.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @authorizationurl /connect/token
// @scope.admin Grants read and write access to administrative information

// @host localhost:8080
// @BasePath /api/v1
func main() {
	migration.Main()

	r := gin.Default()

	// v1 := r.Group("/")
	// {
	user := r.Group("/user")
	{
		user.POST("/create", usercontroller.Create)
		user.GET("/groups", usercontroller.Groups)
	}
	payment := r.Group("/payment")
	{
		payment.POST("/create", paymentcontroller.Create)
	}
	//}

	r.POST("/connect/token", func(c *gin.Context) {
		authenticationcontroller.Authenticate(c)
	})

	config := &ginSwagger.Config{
		URL: "http://localhost:8080/swagger/doc.json"} //The url pointing to API definition }
	r.GET("/swagger/*any", ginSwagger.CustomWrapHandler(config, swaggerFiles.Handler))

	r.Run(":8080")
}

func init() {
	//docs.SwaggerInfo.Title = "API CashAPI"
}

// Handler
func hello(c echo.Context) error {
	return c.String(http.StatusOK, "Hello, World!")
}
